<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partidos [
<!ELEMENT partidos (partido+)>
<!ELEMENT partido (equipolocal, equipovisitante)>
<!ELEMENT equipolocal (#PCDATA)>
<!ATTLIST equipolocal goleslocal #REQUIRED>
<!ELEMENT equipovisitante (#PCDATA)>
<!ATTLIST equipovisitante golesvisitantes #REQUIRED>
]>

<partidos>
<partido>
<equipolocal goleslocal="0">Nottingham Presa</equipolocal>
<equipovisitante golesvisitantes="1">Inter de Mitente</equipovisitante>
</partido>
<partido>
<equipolocal goleslocal="3">Vodka Juniors</equipolocal>
<equipovisitante golesvisitantes="3"> Sparta da Risa</equipovisitante>
</partido>
<partido>
<equipolocal goleslocal="4">Water de Munich</equipolocal>
<equipovisitante golesvisitantes="2"> Esteaua es del grifo</equipovisitante>
</partido>
</partidos>
