<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partidos [
<!ELEMENT partidos (partido+)>
<!ELEMENT partido (equipolocal, equipovisitante, goleslocal, golesvisitantes)>
<!ELEMENT equipo (#PCDATA)>
<!ELEMENT equipovisitante (#PCDATA)>
<!ELEMENT goleslocal (#PCDATA)>
<!ELEMENT golesvisitantes (#PCDATA)>
]>

<partidos>
<partido>
<equipolocal>Nottingham Presa</equipolocal>
<equipovisitante>Inter de Mitente</equipovisitante>
<goleslocal>0</goleslocal>
<golesvisitantes>1</golesvisitantes>
</partido>
<partido>
<equipolocal>Vodka Juniors</equipolocal>
<equipovisitante> Sparta da Risa</equipovisitante>
<goleslocal>3</goleslocal>
<golesvisitantes>3</golesvisitantes>
</partido>
<partido>
<equipolocal>Water de Munich</equipolocal>
<equipovisitante> Esteaua es del grifo</equipovisitante>
<goleslocal>4</goleslocal>
<golesvisitantes>2</golesvisitantes>
</partido>
</partidos>
