<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paises [
<!ELEMENT pais (nombre, unionEuropea)>
<!ELEMENT nombre EMPTY>
<!ELEMENT unionEuropea EMPTY>
]>
<paises>
<pais>
<nombre>Espa√±a</nombre>
<unionEuropea />
</pais>
<pais>
<nombre>Noruega</nombre>
</pais>
<pais>
<nombre>Austria</nombre>
</pais>
</paises>
